import { test, expect } from "@playwright/test";

test("test", async ({ page }) => {
  await page.goto("http://localhost:5173/");
  await page.getByRole("button", { name: "Populate categories" }).click();
  await page.getByRole("link", { name: "Players" }).click();
  await page.getByPlaceholder("First name").click();
  await page.getByPlaceholder("First name").fill("Arthur");
  await page.getByPlaceholder("First name").press("Tab");
  await page.getByPlaceholder("Last name").fill("Peruzzo");
  await page.getByPlaceholder("Last name").press("Tab");
  await page.getByPlaceholder("Email").fill("ozzu@proton.me");
  await page.getByPlaceholder("Email").press("Tab");
  await page.getByLabel("Category").click();
  await page.getByLabel("1").click();
  await page.getByLabel("Position").click();
  await page.getByText("REVES").click();
  await page.getByRole("button", { name: "Submit" }).click();
  await page.getByRole("link", { name: "Players" }).click();
  await page.getByPlaceholder("First name").click();
  await page.getByPlaceholder("First name").press("Control+a");
  await page.getByPlaceholder("First name").fill("Ju");
  await page.getByPlaceholder("First name").press("Tab");
  await page.getByPlaceholder("Last name").press("Control+a");
  await page.getByPlaceholder("Last name").fill("Ju");
  await page.getByPlaceholder("Last name").press("Tab");
  await page.getByPlaceholder("Email").fill("juju@proton.me");
  await page.getByLabel("Position").click();
  await page.getByLabel("DRIVE").click();
  await page.getByRole("button", { name: "Submit" }).click();
  await page.getByRole("link", { name: "Doubles" }).click();
  await page.getByLabel("Player one").click();
  await page.getByLabel("Arthur Peruzzo").click();
  await page.getByLabel("Player two").click();
  await page.getByLabel("Ju Ju").click();
  await page.getByLabel("Category").click();
  await page.getByText("1 ALL").click();
  await page.getByRole("button", { name: "Submit" }).click();
  await page.getByRole("link", { name: "Places" }).click();
  await page.getByPlaceholder("Place name").click();
  await page.getByPlaceholder("Place name").fill("Complexo CK");
  await page.getByPlaceholder("Address").click();
  await page.getByPlaceholder("Address").fill("General Gomes Tortinho, 255.");
  await page.getByRole("button", { name: "Submit" }).click();
  await page.getByRole("link", { name: "Events" }).click();
  await page.getByPlaceholder("Event Name").click();
  await page.getByPlaceholder("Event Name").fill("Copa do Bem");
  await page.getByLabel("Categories").click();
  await page.getByLabel("1").click();
  await page.getByRole("button", { name: "Add Category" }).click();
  await page.getByLabel("Places").click();
  await page.getByLabel("Complexo CK").click();
  await page.getByRole("button", { name: "Add Place" }).click();
  await page.getByRole("button", { name: "Submit" }).click();
  await page.getByRole("button", { name: "Show all events" }).click();
  await page.getByRole("button", { name: "Register in event" }).click();
  await page.getByLabel("Doubles").click();
  await page.getByLabel("Arthur PeruzzoJu Ju").click();
  await page.getByRole("button", { name: "Register Doubles" }).click();
  await page.getByRole("button", { name: "Close event" }).click();
  await page.getByRole("button", { name: "Register in event" }).click();
});
