/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PlayersLazyImport = createFileRoute('/players')()
const PlacesLazyImport = createFileRoute('/places')()
const EventsLazyImport = createFileRoute('/events')()
const DoublesLazyImport = createFileRoute('/doubles')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PlayersLazyRoute = PlayersLazyImport.update({
  path: '/players',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/players.lazy').then((d) => d.Route))

const PlacesLazyRoute = PlacesLazyImport.update({
  path: '/places',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/places.lazy').then((d) => d.Route))

const EventsLazyRoute = EventsLazyImport.update({
  path: '/events',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/events.lazy').then((d) => d.Route))

const DoublesLazyRoute = DoublesLazyImport.update({
  path: '/doubles',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/doubles.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/doubles': {
      preLoaderRoute: typeof DoublesLazyImport
      parentRoute: typeof rootRoute
    }
    '/events': {
      preLoaderRoute: typeof EventsLazyImport
      parentRoute: typeof rootRoute
    }
    '/places': {
      preLoaderRoute: typeof PlacesLazyImport
      parentRoute: typeof rootRoute
    }
    '/players': {
      preLoaderRoute: typeof PlayersLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  DoublesLazyRoute,
  EventsLazyRoute,
  PlacesLazyRoute,
  PlayersLazyRoute,
])

/* prettier-ignore-end */
